service: serverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-1
  lambdaHashingVersion: 20201221
  vpc:
    securityGroupIds:
      - ${ssm:/serverless/lambda_security_group}
    subnetIds:
      - ${ssm:/serverless/lambda_subnet}
    
functions:
  hello:
    handler: handler.hello
    layers:
      - arn:aws:lambda:ap-southeast-1:770693421928:layer:Klayers-python38-requests:20
